### ISSUE TITLE
Plugin Cannot Load

### ISSUE THREAD

**Issue by Time6628** [KaiKikuchi/GriefPreventionPlus-Cities#22]
Getting this error when the plugin tries to load:
```
[11:02:37] [Server thread/ERROR]: [GPPCities] Unable to read the database. Details:
[11:02:37] [Server thread/ERROR]: [GPPCities] null
[11:02:37] [Server thread/WARN]: java.lang.NullPointerException
[11:02:37] [Server thread/WARN]: 	at net.kaikk.mc.gppcities.DataStore.<init>(DataStore.java:220)
[11:02:37] [Server thread/WARN]: 	at net.kaikk.mc.gppcities.GPPCities.onEnable(GPPCities.java:58)
[11:02:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[11:02:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[11:02:37] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[11:02:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
[11:02:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
[11:02:37] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511)
[11:02:37] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485)
[11:02:37] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445)
[11:02:37] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
[11:02:37] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
[11:02:37] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)[11:02:37] [Server thread/ERROR]: [GPPCities] Unable to read the database. Details:
[11:02:37] [Server thread/ERROR]: [GPPCities] null
[11:02:37] [Server thread/WARN]: java.lang.NullPointerException
[11:02:37] [Server thread/WARN]: 	at net.kaikk.mc.gppcities.DataStore.<init>(DataStore.java:220)
[11:02:37] [Server thread/WARN]: 	at net.kaikk.mc.gppcities.GPPCities.onEnable(GPPCities.java:58)
[11:02:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:316)
[11:02:37] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:368)
[11:02:37] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:410)
[11:02:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.loadPlugin(CraftServer.java:415)
[11:02:37] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_7_R4.CraftServer.enablePlugins(CraftServer.java:349)
[11:02:37] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71243_i(MinecraftServer.java:511)
[11:02:37] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:485)
[11:02:37] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.func_71247_a(MinecraftServer.java:445)
[11:02:37] [Server thread/WARN]: 	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:336)
[11:02:37] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
[11:02:37] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
```

**Comment by KaiKikuchi** [comment]
This is a database issue. Check you config.yml and be sure your database settings are correct.

**Comment by Time6628** [comment]
They are.

**Comment by KaiKikuchi** [comment]
Then please provide more info... is it the first time you run the plugin? Plugins version?

**Comment by KaiKikuchi** [comment]
Also try with phpmyadmin to truncate gppc_bans table

**Comment by Time6628** [comment]
I am using the latest plugin version, and I have been using it since the beginning of December.

**Comment by KaiKikuchi** [comment]
Unfortunately I'm not at home so this is the best support I can offer atm with my smartphone. Please try to truncate the gppc bans table

**Comment by Time6628** [comment]
That fixed it, thanks :3.

**Comment by KaiKikuchi** [comment]
Nice to know that! Thank you for reporting this!
